2024-09-27 18:09:11,069 - ERROR - An exception occurred
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    first_scene()
  File "part1.py", line 85, in first_scene
    clock_main_loop()  # Call minigame here
    ^^^^^^^^^^^^^^^^^
  File "clock.py", line 115, in clock_main_loop
    common.fade_in(screen, clockbg, duration=1000)
  File "common.py", line 93, in fade_in
    screen.blit(surface, (0, 0))  # draw image
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pygame.error: display Surface quit
